development: &development
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: ddjc3kgglpblt6 
  pool: 5
  timeout: 5000
  username: ownnldpxrumhze 
  password: aKi2zpzIPb7pIHAMoot5N6M-84 
  host: ec2-107-21-223-72.compute-1.amazonaws.com

test: &test
  <<: *development
  database: ddjc3kgglpblt6

production: &production
  <<: *development
  database: ddjc3kgglpblt6 
